### ISSUE TITLE
Web installation SS 4.0.1 - Parse error: syntax error, unexpected ':', expecting ';' or '{' in /public_html/vendor/symfony/filesystem/Filesystem.php on line 727

### ISSUE THREAD

**Issue by SqualaDesign** [silverstripe/silverstripe-installer#215] opened 2017-12-15 03:20 UTC
## Affected Version
SilverStripe 4.0.1

## Description
I'm trying to install SilverStripe 4.0.1 on my VPS, LAMP technology. All requirements are correct.
![screencapture-205-134-253-41-devsquala-install-php-1513307543231](https://user-images.githubusercontent.com/8541984/34025106-eef0c3de-e1b2-11e7-9624-460680aac7da.png)

## Steps to Reproduce
I'm using the normal web installation and not composer.

**Comment by robbieaverill** [comment] 2017-12-15 04:02
Hey @SqualaDesign would you mind providing the version of PHP you're using please?

**Comment by robbieaverill** [comment] 2017-12-15 04:04
Ah, I think I know what has happened here. You've probably downloaded the archive from the SilverStripe website which was built with PHP 7, and you're running PHP 5.6?

**Comment by robbieaverill** [comment] 2017-12-15 04:08
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7709.

If you need help fixing this, please follow up on that issue.

**Closed by robbieaverill** 2017-12-15 04:08 UTC
