### ISSUE TITLE
"Installing SilverStripe" page doesn't stream

### ISSUE THREAD

**Issue by RantyDave** [silverstripe/silverstripe-installer#88] opened 2015-03-15 04:33 UTC
The successful installation page....

![installing_silverstripe___](https://cloud.githubusercontent.com/assets/4230547/6654688/077ed528-cb39-11e4-987e-44b70b4f2e1c.png)

Gives the impression it is supposed to stream over the bulleted list ("I am now running through the installation steps"). What actually happens is that the install completes and then displays the list. Since there is no "done!" response either there is no indication that the install has actually succeeded.

**Comment by chillu** [comment] 2015-04-26 06:54
Agree its not ideal, particularly since the DB schema step can take a few seconds. Setting session state with the completed steps and some ajax timer would be nicer. Or websockets if we want to get fancy :)

The last step here is usually testing rewrite (see `checkRewrite()` in `framework/dev/install/install.php5`. Do you want to try and get a "done" step showing in the ajax response there?

Otherwise I'm inclined to close this ticket as an enhancement. As you know, open source usually has much more good ideas than are feasible to write code for. Our issue tracking policy is described here: http://docs.silverstripe.org/en/contributing/issues_and_bugs/

**Comment by RantyDave** [comment] 2015-04-26 07:42
All it needs is the word "done" at the bottom. As it is it looks like it's stuck "creating initial filesystem assets". Like in infamous Apple upgrade "completed in one minute". See what I mean?

Don't worry, I'll do it :)

**Comment by RantyDave** [comment] 2015-04-26 08:21
Huh. Can't repeat on 3.1.x-dev. I guess someone else got there first. Mark as closed?

**Comment by chillu** [comment] 2015-04-26 23:52
I don't think its implemented with a "done" step - just installed 3.1.12 and the last step is "friendly URLs set up successfully". See https://github.com/silverstripe/silverstripe-framework/blob/3.1/dev/install/install.php5#L1575. The whole install process is pretty quick here (1-2s, with SSD), so I don't think the "done" step will make much difference. As you can see in the code above, there's an artificial 2s delay before redirecting to "install successful", but that's by design. So closing this off for now, but feel free to dig into the installer and check how we can get better timely feedback to the user :)

**Closed by chillu** 2015-04-26 23:52 UTC
