### ISSUE TITLE
Problem with missing package "php-intl"

### ISSUE THREAD

**Issue by minimalic** [silverstripe/silverstripe-installer#169] opened 2017-04-08 17:05 UTC
Silverstripe 4.0 alpha 6 seems to need `php-intl` but there is no info in the installer. Installing `php-intl` let you install SilverStripe, but without `php-intl` it causes ugly PHP error :)

**Comment by robbieaverill** [comment] 2017-04-20 05:21
This would be useful for those who don't install with composer initially (https://github.com/silverstripe/silverstripe-framework/issues/6627)

**Comment by sminnee** [comment] 2017-04-20 05:24
I'm closing this as a duplicate of 6627 and 6765

**Closed by sminnee** 2017-04-20 05:24 UTC
