### ISSUE TITLE
Composer install of SS4 beta 1 fails

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-installer#187] opened 2017-07-03 08:31 UTC
![screenshot from 2017-07-03 20-28-39](https://user-images.githubusercontent.com/8912185/27784463-3bfce5c4-602e-11e7-8e91-73865913600c.png)

**Comment by kinglozzer** [comment] 2017-07-03 09:12
Try again now @SpiritLevel.

I had to hit the update button in Packagist manually, I’m not sure why... maybe Packagist had a blip, or maybe the token we’re using for the Github service isn’t working anymore

**Comment by SpiritLevel** [comment] 2017-07-03 09:21
This is what I get now :(
![screenshot from 2017-07-03 21-18-24](https://user-images.githubusercontent.com/8912185/27786428-3cd0d92c-6035-11e7-863f-ad79fc549264.png)

**Comment by dhensby** [comment] 2017-07-03 09:21
hmm - there's definitely a dependency resolution error - I'me getting the error too.

in text form:

```
composer create-project silverstripe/installer:4.0.0-beta1 www
Installing silverstripe/installer (4.0.0-beta1)
  - Installing silverstripe/installer (4.0.0-beta1): Downloading (100%)
Created project in www
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package silverstripe/cms 4.0.0-beta1 exists as silverstripe/cms[2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.9, 2.4.x-dev, 2.5.0, 3.0.10, 3.0.10-rc1, 3.0.11, 3.0.11-rc1, 3.0.12, 3.0.13, 3.0.14, 3.0.2.1, 3.0.3, 3.0.3-rc1, 3.0.3-rc2, 3.0.4, 3.0.5, 3.0.6, 3.0.6-rc1, 3.0.6-rc2, 3.0.7, 3.0.7-rc1, 3.0.8, 3.0.9, 3.0.9-rc1, 3.0.x-dev, 3.1.0, 3.1.0-beta1, 3.1.0-beta2, 3.1.0-beta3, 3.1.0-rc1, 3.1.0-rc2, 3.1.0-rc3, 3.1.1, 3.1.10, 3.1.10-rc1, 3.1.10-rc2, 3.1.11, 3.1.11-rc1, 3.1.12, 3.1.13, 3.1.13-rc1, 3.1.14, 3.1.14-rc1, 3.1.15, 3.1.16, 3.1.16-rc1, 3.1.17, 3.1.17-rc1, 3.1.17-rc2, 3.1.18, 3.1.18-rc1, 3.1.18-rc2, 3.1.19, 3.1.19-rc1, 3.1.2, 3.1.2-rc1, 3.1.20, 3.1.20-rc1, 3.1.20-rc2, 3.1.21, 3.1.3, 3.1.3-rc1, 3.1.3-rc2, 3.1.4, 3.1.4-rc1, 3.1.5, 3.1.5-rc1, 3.1.6, 3.1.6-rc1, 3.1.6-rc2, 3.1.6-rc3, 3.1.7, 3.1.7-rc1, 3.1.8, 3.1.9, 3.1.9-rc1, 3.2.0, 3.2.0-beta1, 3.2.0-beta2, 3.2.0-rc1, 3.2.0-rc2, 3.2.1, 3.2.1-rc1, 3.2.1-rc2, 3.2.2, 3.2.2-rc1, 3.2.2-rc2, 3.2.3, 3.2.3-rc1, 3.2.3-rc2, 3.2.4, 3.2.4-rc1, 3.2.5, 3.2.5-rc1, 3.2.5-rc2, 3.2.6, 3.3.0, 3.3.0-beta1, 3.3.0-rc1, 3.3.0-rc2, 3.3.0-rc3, 3.3.1, 3.3.1-rc1, 3.3.1-rc2, 3.3.2, 3.3.2-rc1, 3.3.3, 3.3.3-rc1, 3.3.3-rc2, 3.3.4, 3.4.0, 3.4.0-rc1, 3.4.1, 3.4.1-rc1, 3.4.1-rc2, 3.4.2, 3.4.3, 3.4.3-rc1, 3.4.4, 3.4.4-rc1, 3.4.5, 3.4.5-rc1, 3.4.6, 3.4.6-rc1, 3.4.6-rc2, 3.5.0, 3.5.0-rc1, 3.5.0-rc2, 3.5.0-rc3, 3.5.1, 3.5.1-rc1, 3.5.1-rc2, 3.5.2, 3.5.2-rc1, 3.5.3, 3.5.3-rc1, 3.5.4, 3.5.4-rc1, 3.5.x-dev, 3.6.0, 3.6.0-beta1, 3.6.0-beta2, 3.6.0-rc1, 3.6.1, 3.6.1-alpha1, 3.6.1-alpha2, 3.6.x-dev, 3.x-dev, 3.7.x-dev, 4.0.0-alpha1, 4.0.0-alpha2, 4.0.0-alpha3, 4.0.0-alpha4, 4.0.0-alpha5, 4.0.0-alpha6, 4.0.0-alpha7, 4.0.x-dev, dev-master, dev-post-2.4, 2.5.x-dev] but these are rejected by your constraint.
  Problem 2
    - The requested package silverstripe/siteconfig 4.0.0-beta1 exists as silverstripe/siteconfig[1.0.0, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.9, 3.0.10, 3.0.10-rc1, 3.0.11, 3.0.11-rc1, 3.0.12, 3.0.13, 3.0.14, 3.0.2.1, 3.0.3, 3.0.3-rc1, 3.0.3-rc2, 3.0.4, 3.0.5, 3.0.6, 3.0.6-rc1, 3.0.6-rc2, 3.0.7, 3.0.7-rc1, 3.0.8, 3.0.9, 3.0.9-rc1, 3.1.0, 3.1.0-beta1, 3.1.0-beta2, 3.1.0-beta3, 3.1.0-rc1, 3.1.0-rc2, 3.1.0-rc3, 3.1.1, 3.1.10, 3.1.10-rc1, 3.1.10-rc2, 3.1.11, 3.1.11-rc1, 3.1.12, 3.1.13, 3.1.13-rc1, 3.1.14, 3.1.14-rc1, 3.1.15, 3.1.16, 3.1.16-rc1, 3.1.17-rc1, 3.1.17-rc2, 3.1.2, 3.1.2-rc1, 3.1.3, 3.1.3-rc1, 3.1.3-rc2, 3.1.4, 3.1.4-rc1, 3.1.5, 3.1.5-rc1, 3.1.6, 3.1.6-rc1, 3.1.6-rc2, 3.1.6-rc3, 3.1.7, 3.1.7-rc1, 3.1.8, 3.1.9, 3.1.9-rc1, 3.2.0, 3.2.0-beta1, 3.2.0-beta2, 3.2.0-rc1, 3.2.0-rc2, 3.2.1, 3.2.1-rc1, 3.2.1-rc2, 3.2.2, 3.2.2-rc1, 3.2.2-rc2, 3.2.3, 3.2.3-rc1, 3.2.3-rc2, 3.2.4, 3.2.4-rc1, 3.2.5, 3.2.5-rc1, 3.2.5-rc2, 3.2.6, 3.3.0, 3.3.0-beta1, 3.3.0-rc1, 3.3.0-rc2, 3.3.0-rc3, 3.3.1, 3.3.1-rc1, 3.3.1-rc2, 3.3.2, 3.3.2-rc1, 3.3.3, 3.3.3-rc1, 3.3.3-rc2, 3.3.4, 3.4.0, 3.4.0-rc1, 3.4.1, 3.4.1-rc1, 3.4.1-rc2, 3.4.2, 3.4.3, 3.4.3-rc1, 3.4.4, 3.4.4-rc1, 3.4.5, 3.4.5-rc1, 3.4.6, 3.4.6-rc1, 3.4.6-rc2, 3.5.0, 3.5.0-rc1, 3.5.0-rc2, 3.5.0-rc3, 3.5.1, 3.5.1-rc1, 3.5.1-rc2, 3.5.2, 3.5.2-rc1, 3.5.3, 3.5.3-rc1, 3.5.4, 3.5.4-rc1, 3.5.x-dev, 3.6.0, 3.6.0-beta1, 3.6.0-beta2, 3.6.0-rc1, 3.6.1, 3.6.x-dev, 3.x-dev, 3.7.x-dev, 4.0.0-alpha1, 4.0.0-alpha2, 4.0.0-alpha3, 4.0.0-alpha4, 4.0.0-alpha5, 4.0.0-alpha6, 4.0.0-alpha7, 4.0.x-dev, dev-master] but these are rejected by your constraint.
  Problem 3
    - Installation request for silverstripe/assets 1.0.0-beta1 -> satisfiable by silverstripe/assets[1.0.0-beta1].
    - silverstripe/reports 4.0.0-beta1 requires silverstripe/assets 1.0.x-dev -> satisfiable by silverstripe/assets[1.0.x-dev].
    - Can only install one of: silverstripe/assets[1.0.x-dev, 1.0.0-beta1].
    - Can only install one of: silverstripe/assets[1.0.x-dev, 1.0.0-beta1].
    - Installation request for silverstripe/reports 4.0.0-beta1 -> satisfiable by silverstripe/reports[4.0.0-beta1].
````

**Comment by SpiritLevel** [comment] 2017-07-03 09:25
Perhaps https://github.com/silverstripe/silverstripe-blog/issues/448 and https://github.com/silverstripe/silverstripe-comments/issues/208 are related to the above dependency problems?

**Comment by dhensby** [comment] 2017-07-03 09:30
nope - there you're trying to install 3.x compat versions of modules in a 4.0.0-alpha7 project.

Here the problem is that the beta tag of reports requires the 1.0.x-dev version of a module instead of the 1.0.0-beta1 version, which other modules require. It's impossible for composer to install a single version that satisfies both constraints.

**Comment by dhensby** [comment] 2017-07-03 09:37
So a temp fix is to update the root `composer.json` file and...

```diff
- "silverstripe/reports": "4.0.0-beta1",
+ "silverstripe/reports": "^4.0.0",
```

**Comment by dhensby** [comment] 2017-07-03 09:43
@tractorcow

**Comment by SpiritLevel** [comment] 2017-07-03 09:46
Thanks @dhensby :) Will try,

**Comment by sminnee** [comment] 2017-07-03 20:03
Reports shouldn't rely on a dev branch; it should probably rely on ^4.0.0-beta1.

My suggestion would be to class this as a release error for the reports module and move its beta1 tag, rather than making up a new tag.

**Comment by chillu** [comment] 2017-07-03 20:52
+1, reports shouldn't rely on a dev branch, or rather: It should format its dependencies like the other core modules:

https://github.com/silverstripe/silverstripe-reports/blob/master/composer.json
https://github.com/silverstripe/silverstripe-siteconfig/blob/master/composer.json
https://github.com/silverstripe/silverstripe-admin/blob/master/composer.json
https://github.com/silverstripe/silverstripe-cms/blob/master/composer.json

**Comment by sminnee** [comment] 2017-07-03 21:25
@SpiritLevel is this working for you now? reports beta1 has been fixed.

**Comment by tractorcow** [comment] 2017-07-03 21:28
I've confirmed it's fixed now. Anyone attempting to install beta1 will now get a working install.

**Closed by tractorcow** 2017-07-03 21:28 UTC
Labels: affects/v4, impact/high, type/bug

**Comment by SpiritLevel** [comment] 2017-07-03 22:10
@sminnee Working fine now :)

**Comment by SpiritLevel** [comment] 2017-07-03 22:14
@dhensby I was also able to resolve silverstripe/silverstripe-blog#448 and silverstripe/silverstripe-comments#208 by using `composer require silverstripe/blog dev-master` and `composer require silverstripe/comments dev-master`. I need to learn more about composer!
