### ISSUE TITLE
composer create-project should set up _ss_environment.php

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-installer#123] opened 2016-05-16 04:59 UTC
This follows on from #116 to focus on environment set-up.

Right now, the canonical way of running `composer create-project silverstripe/installer <foldername>`. This does part of the install process, but requires further set-up.

Specifically, you need to visit install.php in a web-browser to populate `_ss_envrionment.php`. Instead of this, it would be best if the CLI-based installation interactively asked the user for database credentials and other details of the new environment, and populated _ss_environment.php for us.

https://github.com/axyr/silverstripe-cli-installer is a start on this, but it requires a separate CLI tool, which shouldn't be necessary, and it duplicates a lot of core functionality. Instead, post-install hooks in silverstripe/installer should check to see if the environment requires configuration, and if so, run an install process based on code provided by framework.

In the first instance, a minimal adaptation of the web installer to CLI execution is probably appropriate.

References:
- https://github.com/axyr/silverstripe-cli-installer
- https://groups.google.com/d/msg/silverstripe-dev/YQ9ru7UuUV0/zWc-1pvwCQAJ

**Comment by stevie-mayhew** [comment] 2016-05-16 07:53
I have a POC for something like this here: https://github.com/stevie-mayhew/silverstripe-installer/tree/feature/installer-process

We use a similar install process locally to set up all of our details, so have just pulled this directly from there.

Would it be worth linking this all up to framework or keeping it separate as part of installer?

**Comment by sminnee** [comment] 2016-05-16 09:49
I think that installer is best thought of as a project skeleton, rather than an application itself, and so putting the meat of the code into framework is best. The install.php does this, it includes code from framework/dev.

**Comment by axyr** [comment] 2016-05-16 12:06
the install5.php that handles the install contains a lot of if/else checking for cli/web and a lot of echo statements that assumes the installer is mainly used by web.

if think a lot of that code could be moved a way in a seperate class, so a cli installer and web installer can use the functions that fits best for the usecases.

Right now that code is hard to re-use if you ask me..

**Comment by sminnee** [comment] 2016-05-16 21:16
Creating a separate class sounds like a reasonable refactoring.

**Comment by tractorcow** [comment] 2016-05-30 03:11
It needs a lot of refactoring. It wouldn't hurt to put a lick of paint on the interface as well. :)

**Comment by JorisDebonnet** [comment] 2016-07-02 15:28
To be honest,.. I have never had a `_ss_environment.php` file in any of my SilverStripe projects. Until recently, I didn't even know why it was in .gitignore. Database credentials have always just ended up in `mysite/_config.php`. 

So if `_ss_environment.php` is a more recommended way (and I would certainly agree, to avoid checking DB credentials into a repository), I guess something somewhere needs to change in the install process indeed :)

**Comment by sminnee** [comment] 2016-07-04 02:20
Yeah, it is more recommended. We create this separation so that you don't need to check your database passwords into your project repos, and create environment-specific `_ss_environment.php` files with the right passwords in them.

install.php already supports the file, with its "Use _ss_environment file for configuration" checkbox.

**Comment by SpiritLevel** [comment] 2016-10-19 23:04
> I think that installer is best thought of as a project skeleton

I am wondering if including a `silverstripe-cache` folder in the webroot would be a good default for a skeleton. If not included, a developer might not put one in, resulting in cache files being written to the fallback, which is often the system `/tmp` folder. This isn't really an issue on local dev machines but writing cache files to `/tmp` on a shared server is probably not a good idea.

**Comment by JorisDebonnet** [comment] 2016-10-19 23:07
I agree, that's another thing I thought about: why not just include `silverstripe-cache` by default. People that don't know what it does are probably benefited by it, and people that do know what it does can remove it if they know what they're doing.

**Comment by dhensby** [comment] 2016-10-31 13:40
> I agree, that's another thing I thought about: why not just include silverstripe-cache by default. People that don't know what it does are probably benefited by it, and people that do know what it does can remove it if they know what they're doing.

I think the issue is that it requires server config to ensure it's writable and often people will 0777 it which is about as secure as putting it in `/tmp`

**Comment by maxime-rainville** [comment] 2020-05-12 22:49
I'm going to close this since `_ss_environment.php` is no longer used with version 4 and it's been 4 years since the issue got any comment.

**Closed by maxime-rainville** 2020-05-12 22:49 UTC
Labels: type/enhancement

**Comment by sminnee** [comment] 2020-05-13 00:01
In SS4 the idea would be to create a .env, but happy to close as a stale enhancement
